# Project: Teste proj
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"C:/Users/user/Desktop/Pastas diversas/GABRIEL/IDEs/Dev-Cpp/MinGW64/lib" -L"C:/Users/user/Desktop/Pastas diversas/GABRIEL/IDEs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -mwindows -lopengl32 -pg -g3
INCS     = -I"C:/Users/user/Desktop/Pastas diversas/GABRIEL/IDEs/Dev-Cpp/MinGW64/include" -I"C:/Users/user/Desktop/Pastas diversas/GABRIEL/IDEs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/user/Desktop/Pastas diversas/GABRIEL/IDEs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/user/Desktop/Pastas diversas/GABRIEL/IDEs/Dev-Cpp/MinGW64/include" -I"C:/Users/user/Desktop/Pastas diversas/GABRIEL/IDEs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/user/Desktop/Pastas diversas/GABRIEL/IDEs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/user/Desktop/Pastas diversas/GABRIEL/IDEs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "Teste proj.exe"
CXXFLAGS = $(CXXINCS) -march=native -mtune=native -pg -g3
CFLAGS   = $(INCS) -march=native -mtune=native -pg -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
